### ISSUE TITLE
Connect the Landing Page with the Dashboard

### ISSUE THREAD

**Issue by segfal** [segfal/layoff_tracker#8]

**Comment by segfal** [comment]
# Make a button where you click the link, it goes to the dashboard. 

The landing page has two buttons, one in the top, and one on the bottom. Both of them should redirect you to the Dashboard.

This will be on [LandingPage.jsx](https://github.com/segfal/layoff_tracker/blob/master/frontend_redux/src/Components/LandingPage.jsx)

Once the dashboard file and css file is uploaded, you should refactor the code so it can connect landing page to dashboard

**Comment by Hikhal** [comment]
Completed.
